### ISSUE TITLE
Consume and display KubeCF icon

### ISSUE THREAD

**Issue by viccuad** [cloudfoundry-incubator/kubecf-docs#12]
Given that KubeCF icon exists: https://raw.githubusercontent.com/cloudfoundry-incubator/kubecf/master/icon/kubecf.png

It could be displayed on the index page of https://kubecf.suse.dev/ as well as a favicon for the tab.

A cursory try showed that the favicon comes from `themes/docsy/assets/` which is a git submodule, and may need to be forked.

**Comment by mook-as** [comment]
According to a [comment in the config file](https://github.com/cloudfoundry-incubator/kubecf-docs/blob/8d8c10d12a0c7c120846e038030cce0b21bb5526/config.toml#L6) we should be able to overlay a custom theme (presumably with a custom icon) on top.

**Comment by mudler** [comment]
This should be fixed now, closing
